# -*- coding: utf-8 -*-
"""trivia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18TXDeQ-hmCqMSvYEaikMwsd7-qj_8bkR
"""

from numpy.random.mtrand import randint
from numpy.core.numeric import count_nonzero
import numpy as np

 
Matriz =[[["¿Qué duración tiene un partido de fútbol que llega a la tanda de penaltis?" , "1. 120  2. 90  3. 95  4. 80"  , 1 ,5] , 
        ["¿De qué colores es la camiseta del Atlético de Madrid?" , "1. Verde y amarillo  2. Rojo y azul  3. Rojo y blanco  4. Blanco y verde" , 3 , 5] ,
        ["¿A qué deporte pertenece la WWE?" , "1. Baloncesto  2. Lucha libre  3. Rugby  4. Fútbol" , 2 , 5],
        ["¿Cómo se llama Iniesta?" , "1. Andrés  2. Johan  3. Felipe  4. Camilo" , 1 , 5],
        ["¿Quién tiene más balones de oro?" , "1. Marco Van Basten  2. Lionel Messi  3. Michel platini  4. Johan Cruyff" , 2, 5]],
       [["¿Qué fruta es la casa de Bob Esponja?" , "1. Una papa  2. Una esponja  3. Una piña  4. No tenía casa" , 3 , 10],
        ["¿Quién es el marido de la actriz Angelina Jolie?", "1. Jared Leto  2. Brad Pitt  3. Timothy Hutton  4. Johan", 2 , 10],
        ["¿En la serie Los Simpson de qué color son las perlas de Lisa?", "1. Moradas  2. Negras  3. Azules  4. Blancas" , 4 , 10],
        ["¿Cuál fue la primera película de Disney?", "1. Pinoccio  2. Dumbo  3. Blancanieves  4. Bambi", 3 , 10],
        ["¿En qué año se estrenó la película de Disney 'Pinoccio'?", "1. 1940  2. 1837  3. 1941  4. 1942", 1, 10]],
       [["¿En qué ciudad de Chile se realiza el festival de la Canción más importante de Latinoamérica?","1.Santiago de Chile  2.Concepción 3.Punt Arenas 4.Viña del Mar",4,10],
        ["¿En qué país está la Costa Azul?", "1. Indonesia  2. Francia  3. Canadá  4. Groenlandia", 2 , 15 ],
        ["¿Cuál es la capital de Noruega?", "1. Bergen  2. Tromso  3. Osolo  4. Trondheim", 3 , 15 ],
        ["¿Cuántas comunidades autónomas hay en España?", "1. 10  2. 12  3. 15  4. 17", 4 , 15],
        ["¿En qué país se encuentra la ciudad de Eindhoven?", "1. Dinamarca  2. Holanda  3. Finlandia  4. Islandia", 2 , 15]],
       [["¿Cómo se llama el estudio de los alimentos?", "1. Bromatología  2. Geología  3. Biología  4. Micología", 1 , 20],
        ["¿De dónde forman parte los axones?", "1. Neurita  2. Célula  3. Neurona  4. Ninguna es correcta", 3, 20],
        ["¿Qué animal puede correr sobre el agua?", "1. Aye Aye  2. Uakari  3. Musaraña elefante 4. Lagarto basilisco", 4 ,20 ],
        ["¿Cuál es la fórmula química del ácido clorhídrico?", "1. 'CIH'  2. 'FeO'  3. 'HCl'  4. 'HO'", 3 , 20 ],
        ["¿Qué es un bacilo?", "1.Una bacteria en forma de bastón  2.Una bacteria en forma de esfera  3.Una bacteria en forma de espiral  4.Una bacteria sin forma", 1, 20 ]],
       [["¿Quién dijo la frase 'miente, miente que algo quedará'?", "1.Markus Meckel  2.Joseph Goebbels 3.Otto von Marchtaler 4.Max Montgelas", 2,25],
        ["¿Cómo se decía en latín la famosa expresión 'La suerte está echada'? ", "1.Cogito, ergo sum 2.Ab imo pectore 3.Acta est fabula 4.Alea iacta est", 4, 25],
        ["¿A qué pueblo derrotó Julio César? ", "1.Helvecios  2.Vénetos  3.Tribus Galas  4.Todas las respuestas son correctas", 4, 25],
        ["¿Qué evento marca el fin de la prehistoria?", "1.Descubrimiento del fuego  2.La escritura  3.Fin de la era glacial  4.Industria microlítica", 2, 25],
        ["¿Cuántos soldados argentinos murieron en la Guerra de las Malvinas? ", "1. 649  2. 650  3. 640  4. 660", 1 , 25]]]
        


valido = 0
count = int(0)
lvl = int(0)
respuesta = int()
print( "Bienvenido a Trivia v1.0.0 " )
print("")
print( "Qué quieres hacer: jugar o salir")
print("")

modo=input()
if modo== "jugar":
  
  for lvl in range (0, 5, 1):

   pregunta = int(randint(0,5))
   print(Matriz[lvl][pregunta][0] , "Puntos acumulados: ",count)
   print("")
   print(Matriz[lvl][pregunta][1])
   respuesta=int(input())
   #lvl= lvl + 1

  
    
        
   
   if respuesta == int(Matriz[lvl][pregunta][2]):
     print("¡Mero teso ñiño!")
     count = count + int(Matriz[lvl][pregunta][3])
     lvl = lvl + 1
   
    
     
    
   else: print("Has perdido!");break

       
else: pass


print( "Juego terminado!, introduce tu nombre...")

nombre = str( input())

print(nombre , "Has puntuado: " , count )

#records= np.array ()
#  """# while valido == 0:
#     if respuesta <= 4:
 #     valido = 1   
  ## while valido == 0:
   #  if bool(isinstance(respuesta, str)) == 1:
    #  valido = 0
     # print("Ingrese valor válido")
      #respuesta=input()
   #while valido == 0:
     #if respuesta >= 5:
      #valido = 0
      #print("Ingrese valor válido")
      #respuesta=input()"""

#Aqui puedes avanzar tu intento en el código